Repository SayedAlesawy/Videra-Storage, pull requests merged in 2020-08, with the labels that each got.

#18 [Feature][Name Node] Add Clips Table
  config/name_node.go
  name_node/models.go
  name_node/namenode.go
  name_node/types.go
Labels: feature

#19 [Feature][Name Node] Added search endpoint
  data_node/controllers/outer/upload_controller.go
  data_node/controllers/outer/utils.go
  name_node/controllers/outer/search_request_controller.go
  name_node/controllers/outer/server.go
  name_node/models.go
  utils/requests/requests.go
Labels: feature

#15 [Feature][DataNode] Add uploaded file type
  config/data_node.go
  data_node/controllers/outer/upload_controller.go
  data_node/controllers/outer/utils.go
  data_node/models.go
  data_node/types.go
  name_node/controllers/outer/upload_request_controller.go
  scripts/fetch_metadata.py
Labels: feature

#20 [Feature][Name Node] Add tags endpoint
  name_node/controllers/outer/server.go
  name_node/controllers/outer/tags_requests_controller.go
Labels: feature

#21 [Fix][Name Node] Use Query Params in Search endpoint
  data_node/controllers/outer/upload_controller.go
  name_node/controllers/outer/search_request_controller.go
  utils/requests/requests.go
Labels: fix

#22 [Fix][Name Node] Decorate tags
  name_node/controllers/outer/search_request_controller.go
  name_node/controllers/outer/tags_requests_controller.go
Labels: fix

#25 [Feature] Add Replication Functioanlity
  config/data_node.go
  data_node/controllers/outer/upload_controller.go
  data_node/datanode.go
  data_node/replication/cache.go
  data_node/replication/replication.go
  data_node/replication/types.go
  data_node/replication/utils.go
  data_node/types.go
  go.mod
  go.sum
  name_node/controllers/outer/replication_controller.go
  name_node/controllers/outer/server.go
Labels: feature

#28 [Feature] Add video token arg to ingest
  data_node/ingest/ingest.go
Labels: enhancement

#27 [Feature] Add video streaming encoding
  config/data_node.go
  data_node/controllers/outer/upload_controller.go
  data_node/stream/stream.go
Labels: feature

#29 [Feature] Add streaming server
  data_node/controllers/outer/server.go
  data_node/controllers/outer/streaming_controller.go
Labels: feature

#30 [Feature] Add thumbnail generation
  config/data_node.go
  data_node/controllers/outer/upload_controller.go
  data_node/models.go
  data_node/thumbnail/thumbnail.go
Labels: feature

#32 [Documentation] Added FE contract V1
  README.md
Labels: documentation

#33 [Fix] Update search endpoint results
  name_node/controllers/outer/search_request_controller.go
  name_node/utils.go
Labels: enhancement, feature, fix

#34 [Feature] Add stream endpoint
  name_node/controllers/outer/server.go
  name_node/controllers/outer/stream_request_controller.go
Labels: feature

#38 [Feature] Added GPU status to JoinClusterRequest
  config/data_node.go
  data_node/datanode.go
  data_node/health.go
  data_node/types.go
  data_node/utils.go
  name_node/controllers/inner/join_cluster_controller.go
  name_node/controllers/outer/upload_request_controller.go
  name_node/nnpb/nnpb_routes.pb.go
  name_node/nnpb/nnpb_routes.proto
  name_node/types.go
  name_node/utils.go
Labels: enhancement, feature

#39 [Fix] Fix a bug in choosing a machine for upload
  name_node/controllers/outer/upload_request_controller.go
Labels: fix

#40 [Fix][Name Node] Load balance based on the last request timestamp
  name_node/controllers/outer/upload_request_controller.go
  name_node/types.go
  name_node/utils.go
Labels: fix

#36 [Feature] Add ingestion status to stream API
  data_node/controllers/outer/server.go
  name_node/controllers/outer/stream_request_controller.go
Labels: feature

#37 [Feature] Add jobs scheduler
  config/data_node.go
  data_node/ingest/ingest.go
  data_node/jobs_scheduler/jobscheduler.go
  data_node/jobs_scheduler/types.go
  data_node/jobs_scheduler/utils.go
  data_node/stream/stream.go
  data_node/thumbnail/thumbnail.go
Labels: feature
