Repository SayedAlesawy/Videra-Storage, pull requests merged in 2020-06, with the labels that each got.

#4 [Feature] Implement NameNode/DataNode Service Discovery
  data_node/datanode.go
  data_node/entrypoint/main.go
  data_node/health.go
  data_node/types.go
  go.mod
  go.sum
  name_node/controllers/inner/join_cluster_controller.go
  name_node/controllers/inner/server.go
  name_node/entrypoint/main.go
  name_node/health.go
  name_node/types.go
  ndpb/routes.pb.go
  ndpb/routes.proto
Labels: WIP, feature

#5 [Feature] Move hard coded values to env vars
  config/config.go
  config/data_node.go
  config/name_node.go
  config/types.go
  data_node/datanode.go
  go.mod
  go.sum
  name_node/controllers/inner/server.go
Labels: feature

#3 [Feature][DataNode] Add upload endpoint
  config/data_node.go
  data_node/entrypoint/main.go
  data_node/types.go
  data_node/upload_manager.go
  data_node/utils.go
  go.mod
  go.sum
Labels: feature

#7 [Feature][UploadManager] Add append request
  config/data_node.go
  data_node/types.go
  data_node/upload_manager.go
  data_node/utils.go
Labels: feature

#8 [Feature] Persist Data Node Info for Tracking
  config/config.go
  config/data_node.go
  config/name_node.go
  config/redis.go
  data_node/controllers/inner/server.go
  data_node/datanode.go
  data_node/health.go
  data_node/types.go
  data_node/upload_manager.go
  data_node/utils.go
  drivers/redis/redis.go
  drivers/redis/types.go
  go.mod
  go.sum
  name_node/cache.go
  name_node/controllers/inner/join_cluster_controller.go
  name_node/controllers/inner/server.go
  name_node/health.go
  name_node/namenode.go
  name_node/nnpb/nnpb_routes.pb.go
  name_node/nnpb/nnpb_routes.proto
  name_node/types.go
  name_node/utils.go
  utils/errors/errors.go
Labels: feature

#9 [Feature][NameNode] Add external upload API
  config/name_node.go
  name_node/controllers/inner/join_cluster_controller.go
  name_node/controllers/outer/server.go
  name_node/controllers/outer/upload_request_controller.go
  name_node/entrypoint/main.go
  name_node/health.go
  name_node/types.go
  name_node/utils.go
Labels: feature

#10 [Fix] Add HTTP Port to Join Cluster Request
  data_node/datanode.go
  data_node/health.go
  data_node/types.go
  data_node/upload_manager.go
  name_node/controllers/inner/join_cluster_controller.go
  name_node/controllers/outer/server.go
  name_node/nnpb/nnpb_routes.pb.go
  name_node/nnpb/nnpb_routes.proto
  name_node/utils.go
Labels: fix

#12 [Feature] Integrate Database
  config/data_node.go
  config/database.go
  data_node/controllers/outer/server.go
  data_node/controllers/outer/upload_controller.go
  data_node/datanode.go
  data_node/models.go
  data_node/types.go
  data_node/utils.go
  go.mod
  go.sum
  utils/database/database.go
  utils/database/types.go
Labels: WIP, feature

#11 [Refactor][DataNode] refactor upload controller
  config/data_node.go
  config/database.go
  data_node/controllers/outer/server.go
  data_node/controllers/outer/upload_controller.go
  data_node/controllers/outer/utils.go
  data_node/datanode.go
  data_node/entrypoint/main.go
  data_node/models.go
  data_node/types.go
  data_node/upload_manager.go
  data_node/utils.go
  go.mod
  go.sum
  utils/database/database.go
  utils/database/types.go
Labels: refactor

#17 [Fix][NameNode] Handle gRPC connection leak
  name_node/health.go
Labels: bug, fix
